language: ruby
rvm:
  - 2.2.0
script: bundle exec rake ci
before_script:
  - jdk_switcher use oraclejdk8
notifications:
  slack:
    secure: G5oh8qllWW1GnB+qpenThnem/1+Gb4wLN3Y3vDQGdWrjSqM1Ey3hN9ME5kXde6lLWlG2ZGF0/dCRDVZUp0rysEfNBnJ5wzL4YoAxpz1CoNvh9FdzVnjqLZ+0EmsXFNlK5E2C49AZrsLpy81/DrxKTn5Ueg7Obk9ck0U2e4ZgF594I6gpmrGsqe6JL/Aq2ORE/s6YXDhfL6O1vboLEhfRKlxcfqEh1ORw8HDXPN53fBwWr6vwaITxhBjYlX1esZwJQdeUch6CG2dmEZenLtKSm42wg8lWlmh0TYM6NrINY+xXkANWvCVd3+EP03oioBsGI9aP8ioyBgAY8xpp3XQkxI0i95jJcf+BU748Dep75dRjnJQVPbBna+JNIy0YAAVF2FkUrxWfjfJdx4h7S5OTMmNYIfbEpH6kkO6BBczAyJeHi1x/9bwnvQZOBgPq4feEdMSfslXJ5rlUwT2sJ4LS7ORBKdyMrXDnEXTj8fynaI58QyIYafTbUShOJRaBFE7YjF8zdg0jcXmaqjkTjf97DQA60nA7RxEZGVAdy/MloetKOEMljRP320iJs+a6RMthB1deuEE5Tml+ME1aPFc9gaJ4TCGmC0hGZF+/UKncnzXyD4MPMRs1e3s9KbMHnYSriPDqK8v0lVD8Fj31HaQJTwX5/W2e7EaXc6Ifl030kkE=
